services:
  ##############################################################################
  # PODS
  ##############################################################################
  css0:
    # profiles: [ "pod", "backend" ]
    image: solidproject/community-server:7
    ports:
      - "3000:3000"
    environment:
      - CSS_BASE_URL=http://localhost:3000
      - CSS_PORT=3000
      - CSS_CONFIG=/config/server.json
      - CSS_SEED_CONFIG=/config/css-users.json
    volumes:
      - type: bind
        source: ./css/pod-template
        target: /config/pod-template
      - type: bind
        source: ./css/css-users.json
        target: /config/css-users.json
      - type: bind
        source: ./css/css.json
        target: /config/server.json
      # - type: bind
      #   source: ./custom-css
      #   target: /custom-css  
      # these lines allow an easy view on what's in the pod's data  
      # - type: bind
      #   source: ./docker-run/data/css0
      #   target: /data
      # these lines make the current computer's users and groups available in the container
      # - /etc/passwd:/etc/passwd:ro
      # - /etc/group:/etc/group:ro
    healthcheck:
      test: "[ -e healthy.flag ] || if wget --no-check-certificate http://localhost:3000/ --spider; then touch healthy.flag; else false; fi"
      interval: 15s
      timeout: 10s
      retries: 65
      start_period: 30s

