sequenceDiagram
  autonumber
  participant a as Actor A
  participant b as Actor B
  participant p as A's Solid Pod
  participant anch as AnchoringRepo
  participant bc as Blockchain


  a ->> a: Create data record

  a ->> a: Create VC from data record
  
  critical Action: Store VC
    a ->> p: POST(VC)
    p ->> a: Response (200, URI VC)
  end
  critical Action: Set ACL
    a ->> p: Request to set ACL for VC %% TODO: detail
    p ->> a: Response %% TODO: detail
  end
  critical Action: Anchor VC on BC
    a --> anch: Anchror(VC, VC_URI)
    anch --> anch: Compute H_VC = Hash(VC)
    anch --> bc: Anchor (H_VC, VC_URI, ContractAddress)
    bc ->> anch: Response
    anch ->> a: Response
  end

