sequenceDiagram
  autonumber
  participant a as Actor A
  participant b as Actor B
  participant p as A's Solid Pod
  participant bc as Blockchain
  %% participant vcApp as VC App

  a ->> a: Create Shipment Record

%%  critical Action Ship Product
%%    Note left of a: Not sure whether it <br/> is needed to post the non-VC version <br/> of the shipment record.
%%    a ->> p: POST (Shipment Record)
%%    p ->> a: Response (200, URI Shipment Record)
%%  end

  
  a ->> a: Create VC
  
  critical Action: Store VC
    a ->> p: POST(VC(Shipment Record))
    p ->> a: Response (200, URI VC(Shipment Record))
  end
  critical Action: Anchor VC on BC
      a ->> bc: Broadcast Message as did:firefly:actorA <br/> (Message = {URI_VC: URI VC(Shipment Record), hash: Hash(Canon(VC))})
      bc ->> a: Response Object (/messages/broadcast) <br/> including batch id, data hash, message hash, txtype, state, …
  end

  a ->> b: Send Message( URI VC(Shipment Record) )

  critical Action: Verify VC

    critical Step1
        b ->> bc: Lookup VC_URI on BC
        bc ->> b: Response Object (data hash, message hash, txtype, state, canonHash)
    end

    critical Step2
        b ->> p: GET( URI VC(Shipment Record) )
        p ->> b: VC_SHIPMENT_RECORD = Response VC(Shipment Record)
    end

    critical Step3: Locally compute hash value from VC
        b -> b: LOCAL_HASH = Hash( Canon(VC_SHIPMENT_RECORD) )
    end

    critical Step4: Compare locally computed hash with the hash retrieved from the BC
        b -> b: Compare (LOCAL_HASH === VC_TRANSACTION_HASH)
        b -> b: Verify_VC(VC_SHIPMENT_RECORD)
        b ->> b: Verify VC(Shipment Record)
    end
end

  
